### ISSUE TITLE
Images on Pin show page are not interactable

### ISSUE THREAD

**Issue by scytherswings** [IlluminusLimited/Frontend#115]
https://app-prod.pinster.io/pin/93eb444e-4a02-49c5-b692-0afe0cca9216 has two images, but only the default is selected and the other image is not clickable to show in the big viewer. The expected behavior is that I should be able to click on either thumbnail in the bottom and have that change the main image display.

**Comment by stretch1414** [comment]
Yeah, the Pin page needs refactored when we extract it away from being only accessible from the collections section.
