### ISSUE TITLE
Collections that contain pins have placeholder images

### ISSUE THREAD

**Issue by BrightRaven** [IlluminusLimited/Frontend#132]
The Collections images - as in the image that represents a collection as a whole - should not be a placeholder, even if the collection is empty. Currently it displays the 300x300 grey image placeholder both when a collection is empty and when it contains images. I suggest we need to either pull a collage of the images inside the collection or allow users to select from a list of images/clipart to represent the collection. We could add simple art like a heart for favorites, a star for traders, a lock for keepers, etc.

**Comment by BrightRaven** [comment]
<img width="700" alt="screen shot 2018-06-20 at 3 17 05 pm" src="https://user-images.githubusercontent.com/39869051/41679770-48f88e8e-749d-11e8-94db-32f66e387a47.png">

**Comment by markmoser** [comment]
Is this still a thing? I don't think so unless you are wanting this to bring in the pintstack thing from the html prototypes
