### ISSUE TITLE
When logging in the save button appears to do nothing

### ISSUE THREAD

**Issue by BrightRaven** [IlluminusLimited/Frontend#148]
If you enter information as a new user and click save, it does nothing. This should either log you in completely and redirect to the home page or it should be a separate button from a login button that doesn't yet exist. (My user doesn't have any additional permissions in Auth 0.)

**Comment by markmoser** [comment]
I'm not following this. Entering info from the settings/profile page while not logged in?

**Comment by markmoser** [comment]
Oh I get it, you want a toast message, or redirect back to home, or some other confirmation.
