### ISSUE TITLE
Can't change the year of a pin, reverts to 2019. Won't publish pins that aren't 2019

### ISSUE THREAD

**Issue by BrightRaven** [IlluminusLimited/Frontend#182]
The Uploader automatically populates 2019 as the year of the pin. You can change and save this, but when you go to publish the pin, it has reverted to 2019 again.

If you try to change the year in the publisher and save it, it reverts to 2019 if you reload it and view it without publishing.

If you try to publish a pin after changing the year, it appears to save it, but won't publish, and again reverts to 2019.

I expect to be able to change the year in both the uploader and the publisher and have it save and publish successfully, and then categorize it correctly by year in the list view on the main page of the app (and eventually the web frontend when we get that working)

I can reproduce this on Windows and Mac. I don't think it has anything to do with the platform though.

**Comment by markmoser** [comment]
@BrightRaven When you have a chance, can you check that I really fixed this on develop? If so I'll ship it to prod.

**Comment by BrightRaven** [comment]
Seems like this is half fixed. I can now edit a pin's year successfully but I can't upload a pin with any year other than 2019

**Comment by markmoser** [comment]
Thanks, will look again

**Comment by markmoser** [comment]
@BrightRaven Should be good to go in production even.
