### ISSUE TITLE
Refactor HTML/CSS class names to be more indicative of the data they represent

### ISSUE THREAD

**Issue by stretch1414** [IlluminusLimited/Frontend#34]
Since we are reusing some logic between pins and assortments, it would be good for the class names to not have 'pin' in them, unless it is something specific for a pin that isn't for an assortment, and vice versa.  Not a big deal, but something that may make the code more clear.

**Comment by markmoser** [comment]
related #139

**Comment by markmoser** [comment]
this will happen along the regroup rewrite
